version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "golang/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: "gradle"
    directory: "java/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: "nuget"
    directory: "dotnet/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: "pip"
    directory: "python/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: "npm"
    directory: "vue/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
  - package-ecosystem: "npm"
    directory: "node/"
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
