/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package javademo

import spock.lang.Specification
import spock.lang.Unroll

class AppTest extends Specification {
    @Unroll
    def "application has '#expected' when greeting is '#greeting'"(String greeting, String expected) {
        setup:
        // App app = new App();
        App app;
        if (greeting == null) {
            app = new App()
        } else {
            app = new App(greeting)
        }

        when:
        String result = app.greeting

        then:
        result == expected
        
        where:
        greeting       | expected
        null           | "Hello World!"
        "Γεια!"        | "Γεια!" 
        "¡Hola!"       | "¡Hola!"
        "Bonjour!"     | "Bonjour!"
        "Buon Giorno!" | "Buon Giorno!"
        "こんにちは!"    | "こんにちは!"
    }
}
